### PR TITLE
Remove redundant subscriptions from ClusterImpl#isShutdown

### PR DESCRIPTION
**Pull request by sashapolo**
Currently, `ClusterImpl#isShutdown` creates a subscription on `onShutdown` by calling `toFuture` and immediately discards it every time this method is called. This may result in a lot of extra allocations when it is called frequently, since these subscriptions are placed into an internal array and are kept there until the sink emits a signal. Since the result of these subscriptions is never used, this PR tries to optimize this method by introducing a volatile flag.

### CODE REVIEW

**Comment by sashapolo** [comment]
Sorry guys, just a gentle ping, can you please have a look?

**Comment by segabriel** [comment]
Hi
1) What is a reason to call/poll it so often? There is an ability to subscribe on its event, see `onShutdown()`.
2) My suggestion: just delete this method `boolean isShutdown();` at all. @artem-v WDYT?

**Comment by artem-v** [comment]
> Hi
> 
> 1. What is a reason to call/poll it so often? There is an ability to subscribe on its event, see `onShutdown()`.
> 2. My suggestion: just delete this method `boolean isShutdown();` at all. @artem-v WDYT?

I agree. Let's remove it.  
It's only being used in one place in one example runner called `io.scalecube.cluster.ClusterTest`.

**Comment by sashapolo** [comment]
Thanks! I will remove it, as suggested

**Pull request closed without merging**
